name: morse_solver
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - h5py
  - pytest
  - click
  - typer
  - rich
  - mpi4py
  - mpich
  - pyscf
  - pyberny
  - tqdm
  - packaging
  - pip
  - pip:
      - geometric==1.1
      - networkx==3.5
      - pyscf-dispersion
