name: morse_solver
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - h5py
  - click
  - colorama
  - tqdm
  - rich
  - typer
  - pyscf
  - pyberny
  - pip
  - setuptools
  - wheel